import React from 'react'
import './home.scss'
const Home = () => {
  return (
    <div className="home">
      home works!
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>
      <h1>Homee</h1>

    </div>
  )
}

export default Home
